#!/bin/sh
# Installs this release's programs on Linux and macOS, from the GitHub
# release this script was published with. Generated by go-selfupdate-lib's
# build workflow from the program's release spec
# (docs/decisions/0014-MADR-shared-installer-templates.md); do not edit a
# published copy.
#
#   curl -fsSL https://github.com/<owner>/<repo>/releases/latest/download/install.sh | sh
#   curl -fsSL https://github.com/<owner>/<repo>/releases/download/<tag>/install.sh | sh -s -- --dir ~/bin
#
# Every file is fetched from this release's tag over HTTPS and checked
# against its SHA256SUMS before anything is installed. It never uses sudo.
#
# Exit codes: 0 installed; 1 a usage or environment error; 2 a
# verification failure, with nothing changed or the previous binary
# restored; 3 installed, but an after_install hook failed.

# >>> selfupdate-release values
# The build workflow replaces this block with the release's values; the
# ones below are the template's samples.
REPOSITORY='maccavelli/relay'
TAG='v1.2.3'
CHANNELS='rc beta'
INSTALLER_NAME='relay'
ENV_PREFIX='RELAY'
PRODUCTS='relay relayctl'
ASSETS='relay linux amd64 relay-linux-amd64 binary
relay linux arm64 relay-linux-arm64.gz gz
relay darwin arm64 relay-darwin-arm64.tar.gz tar.gz
relayctl linux amd64 relayctl-linux-amd64 binary
relayctl linux arm64 relayctl-linux-arm64.gz gz
relayctl darwin arm64 relayctl-darwin-arm64.tar.gz tar.gz'
IDENTITY='relay version'
HOOKS='before_install relayctl service stop --if-running
after_install relay configure'
# <<< selfupdate-release values

PUBLISH_WORKFLOW='maccavelli/go-selfupdate-lib/.github/workflows/publish-selfupdate-release.yml'

say() {
	printf '%s\n' "$*"
}

err() {
	printf 'install: %s\n' "$*" >&2
}

# die CODE MESSAGE: report and exit.
die() {
	err "$2"
	exit "$1"
}

usage() {
	cat <<EOF
Installs $PRODUCTS from $REPOSITORY $TAG.

Usage: install.sh [options]
  --version TAG          install another release (default $TAG)
  --dir DIR              install into DIR (default ~/.local/bin)
  --product NAME         install only NAME; repeatable (default: all)
  --verify-attestation   also verify each download's attestation with gh
  --no-hooks             skip the release's install hooks
  --allow-root           allow running as root
  --dry-run              show what would be done, and change nothing
  --uninstall            remove the programs (configuration is left)
  --help                 show this help

Environment: ${ENV_PREFIX}_VERSION, ${ENV_PREFIX}_INSTALL_DIR, ${ENV_PREFIX}_NO_HOOKS=1
EOF
}

# env_get NAME: the value of the variable <ENV_PREFIX>_NAME, or empty.
# ENV_PREFIX and NAME are both [A-Z0-9_], so the eval is safe.
env_get() {
	eval "printf '%s' \"\${${ENV_PREFIX}_$1:-}\""
}

# set_base: the download origin and the transport options. A loopback http
# origin is allowed only for tests; anything else must be https.
set_base() {
	BASE=${SELFUPDATE_INSTALL_BASE_URL:-https://github.com}
	BASE=${BASE%/}
	case $BASE in
	https://*)
		CURL_PROTO='=https'
		WGET_HTTPS_ONLY=1
		;;
	http://127.0.0.1:* | http://localhost:*)
		# Only a port may follow, or "localhost:@host" would be a user
		# name and another host.
		case ${BASE#http://*:} in
		'' | *[!0-9]*) die 1 "SELFUPDATE_INSTALL_BASE_URL must be an https:// URL, or a loopback http:// one" ;;
		esac
		CURL_PROTO='=http,https'
		WGET_HTTPS_ONLY=0
		;;
	*) die 1 "SELFUPDATE_INSTALL_BASE_URL must be an https:// URL, or a loopback http:// one" ;;
	esac
}

# fetch URL FILE: download URL to FILE, failing on any HTTP error.
fetch() {
	if command -v curl >/dev/null 2>&1; then
		curl --proto "$CURL_PROTO" --tlsv1.2 --fail --silent --show-error --location \
			--retry 3 --connect-timeout 20 --output "$2" "$1"
	elif command -v wget >/dev/null 2>&1; then
		if [ "$WGET_HTTPS_ONLY" = 1 ]; then
			# BusyBox wget has no --https-only; refuse it rather than risk
			# a downgrade.
			wget --help 2>&1 | grep -q -- '--https-only' ||
				die 1 "this wget cannot refuse plain http (no --https-only); install curl"
			wget --https-only -q -O "$2" "$1"
		else
			wget -q -O "$2" "$1"
		fi
	else
		die 1 "curl or wget is required"
	fi
}

# hash_of FILE: the file's SHA-256, in lower-case hex. Each tool reads the
# file from its standard input: sha256sum and shasum escape a name holding
# a backslash, prefixing the hash with "\".
hash_of() {
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum <"$1" | cut -d' ' -f1 | tr 'A-F' 'a-f'
	elif command -v shasum >/dev/null 2>&1; then
		shasum -a 256 <"$1" | cut -d' ' -f1 | tr 'A-F' 'a-f'
	elif command -v openssl >/dev/null 2>&1; then
		openssl dgst -sha256 -r <"$1" | cut -d' ' -f1 | tr 'A-F' 'a-f'
	else
		die 1 "sha256sum, shasum or openssl is required to verify the download"
	fi
}

# sum_for FILE NAME: print the one hash SHA256SUMS lists for NAME. A line
# counts only as exactly "<64 lower-case hex>  NAME"; a CR, a short hash or
# a second line for NAME fails. Exit 0 found; 3 no line; 1 bad or twice.
sum_for() {
	awk -v n="$2" '
		length($0) == 66 + length(n) && substr($0, 65, 2) == "  " && substr($0, 67) == n {
			h = substr($0, 1, 64)
			if (h ~ /[^0-9a-f]/) { bad = 1 } else { c++; v = h }
		}
		END {
			if (bad || c > 1) exit 1
			if (c == 0) exit 3
			print v
		}' "$1"
}

# check_tag TAG: the tag rule, and the release's prerelease channels.
check_tag() {
	# grep matches line by line, so a newline is refused first.
	case $1 in
	'' | *[!A-Za-z0-9.-]*) die 1 "$1 is not a release tag (vMAJOR.MINOR.PATCH)" ;;
	esac
	printf '%s\n' "$1" | grep -Eq '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[a-z][a-z0-9]{0,15}\.(0|[1-9][0-9]*))?$' ||
		die 1 "$1 is not a release tag (vMAJOR.MINOR.PATCH)"
	case $1 in
	*-*)
		chan=${1#*-}
		chan=${chan%%.*}
		case " $CHANNELS " in
		*" $chan "*) ;;
		*) die 1 "$1 is a prerelease on channel $chan, which this release does not publish" ;;
		esac
		;;
	esac
}

# detect_platform: OS and ARCH as Go names. A shell under Rosetta on Apple
# silicon reports x86_64; the native machine is arm64.
detect_platform() {
	case $(uname -s) in
	Linux) OS=linux ;;
	Darwin) OS=darwin ;;
	*) OS=$(uname -s | tr '[:upper:]' '[:lower:]') ;;
	esac
	case $(uname -m) in
	x86_64 | amd64) ARCH=amd64 ;;
	aarch64 | arm64) ARCH=arm64 ;;
	*) ARCH=$(uname -m) ;;
	esac
	if [ "$OS" = darwin ] && [ "$ARCH" = amd64 ] &&
		[ "$(sysctl -n sysctl.proc_translated 2>/dev/null || true)" = 1 ]; then
		ARCH=arm64
	fi
}

# asset_for PRODUCT: "<asset> <format>" for this platform, or nothing.
asset_for() {
	printf '%s\n' "$ASSETS" | awk -v p="$1" -v o="$OS" -v a="$ARCH" '$1 == p && $2 == o && $3 == a { print $4 " " $5 }'
}

# supported: the platforms this release ships, for an error message.
supported() {
	printf '%s\n' "$ASSETS" | awk '{ print $2 "/" $3 }' | sort -u | tr '\n' ' '
}

# run_hooks WHEN DIR: run each hook of that time. before_install runs the
# installed copy, and skips a product not installed yet.
run_hooks() {
	[ "$NO_HOOKS" = 1 ] && return 0
	[ -n "$HOOKS" ] || return 0
	hooks_failed=0
	set -f
	# The arguments match [A-Za-z0-9._:=/,+@%-], so splitting on spaces is
	# exact (0014-PLAN deviation D1).
	printf '%s\n' "$HOOKS" >"$WORK/hooks"
	while read -r when prod args; do
		[ "$when" = "$1" ] || continue
		selected "$prod" || continue
		exe="$2/$prod"
		if [ ! -f "$exe" ] || [ ! -x "$exe" ]; then
			continue
		fi
		say "running $prod $args"
		# shellcheck disable=SC2086 # args is a word list on purpose.
		# Not the list's file as stdin, which the hook could read up.
		if ! "$exe" $args </dev/null; then
			err "$1 hook failed: $prod $args"
			hooks_failed=1
			[ "$1" = before_install ] && break
		fi
	done <"$WORK/hooks"
	set +f
	return "$hooks_failed"
}

# in_list WORD LIST: whether WORD is one of LIST's space-separated words.
in_list() {
	case " $2 " in
	*" $1 "*) return 0 ;;
	esac
	return 1
}

# selected PRODUCT: whether PRODUCT is among the products to install.
selected() {
	case " $SELECTED " in
	*" $1 "*) return 0 ;;
	esac
	return 1
}

# check_identity DIR: each installed product with an identity command must
# print "<tag> (release)" first, with or without the commit.
check_identity() {
	[ -n "$IDENTITY" ] || return 0
	set -f
	printf '%s\n' "$IDENTITY" >"$WORK/identity"
	while read -r prod args; do
		selected "$prod" || continue
		# shellcheck disable=SC2086 # args is a word list on purpose.
		first=$("$1/$prod" $args 2>/dev/null </dev/null | head -n 1) || true
		case $first in
		"$VERSION (release)" | "$VERSION (release) "????????????) ;;
		*)
			set +f
			err "$prod reports \"$first\", not $VERSION (release)"
			return 1
			;;
		esac
	done <"$WORK/identity"
	set +f
	return 0
}

# restore DIR: put back every binary this run replaced, and remove new ones
# that had no predecessor. A .prev an earlier run left is not this run's.
restore() {
	for prod in $SWAPPED; do
		if in_list "$prod" "$PREVIOUS"; then
			mv -f "$1/$prod.prev" "$1/$prod"
		else
			rm -f "$1/$prod"
		fi
	done
}

cleanup() {
	if [ -n "${WORK:-}" ] && [ -d "$WORK" ]; then
		rm -rf "$WORK"
	fi
}

uninstall() {
	for prod in $SELECTED; do
		if [ "$DRY_RUN" = 1 ]; then
			say "would remove $DIR/$prod"
			continue
		fi
		rm -f "$DIR/$prod" "$DIR/$prod.prev"
		say "removed $DIR/$prod"
	done
	say "configuration, if any, is left in place"
}

# fetch_verified NAME FILE: find NAME in SHA256SUMS, download it to FILE
# and check it; exit 2 on a mismatch. A release that does not list NAME is
# refused before anything is downloaded.
fetch_verified() {
	rc=0
	want=$(sum_for "$WORK/SHA256SUMS" "$1") || rc=$?
	case $rc in
	0) ;;
	3)
		if [ "$VERSION" != "$TAG" ]; then
			die 1 "release $VERSION has no $1; its own installer is $BASE/$REPOSITORY/releases/download/$VERSION/install.sh"
		fi
		die 2 "SHA256SUMS has no entry for $1"
		;;
	*) die 2 "SHA256SUMS has a malformed or duplicate entry for $1" ;;
	esac
	fetch "$BASE/$REPOSITORY/releases/download/$VERSION/$1" "$2" || die 2 "download of $1 failed"
	got=$(hash_of "$2")
	[ "$got" = "$want" ] || die 2 "$1: SHA-256 $got does not match SHA256SUMS ($want)"
	if [ "$VERIFY_ATTESTATION" = 1 ]; then
		gh attestation verify "$2" --repo "$REPOSITORY" --signer-workflow "$PUBLISH_WORKFLOW" >/dev/null ||
			die 2 "$1: attestation verification failed"
	fi
}

# extract PRODUCT FILE FORMAT DEST: put the program from FILE at DEST.
extract() {
	case $3 in
	binary) mv "$2" "$4" ;;
	tar.gz) tar -xzf "$2" -C "$WORK" "$1" && mv "$WORK/$1" "$4" ;;
	gz) gzip -dc "$2" >"$4" ;;
	zip)
		command -v unzip >/dev/null 2>&1 || die 1 "unzip is required for a zip release"
		unzip -o -q "$2" "$1" -d "$WORK" && mv "$WORK/$1" "$4"
		;;
	*) die 1 "unknown archive format $3" ;;
	esac
}

main() {
	set -eu
	umask 022
	VERSION=''
	DIR=''
	SELECTED=''
	VERIFY_ATTESTATION=0
	NO_HOOKS=0
	ALLOW_ROOT=0
	DRY_RUN=0
	UNINSTALL=0
	WORK=''
	SWAPPED=''
	PREVIOUS=''
	while [ $# -gt 0 ]; do
		case $1 in
		--version) [ $# -ge 2 ] || die 1 "--version needs a tag"; VERSION=$2; shift 2 ;;
		--dir) [ $# -ge 2 ] || die 1 "--dir needs a directory"; DIR=$2; shift 2 ;;
		--product)
			[ $# -ge 2 ] || die 1 "--product needs a name"
			case $2 in
			'' | *[!A-Za-z0-9._-]*) die 1 "--product needs a product name, not \"$2\"" ;;
			esac
			SELECTED="$SELECTED $2"
			shift 2
			;;
		--verify-attestation) VERIFY_ATTESTATION=1; shift ;;
		--no-hooks) NO_HOOKS=1; shift ;;
		--allow-root) ALLOW_ROOT=1; shift ;;
		--dry-run) DRY_RUN=1; shift ;;
		--uninstall) UNINSTALL=1; shift ;;
		-h | --help) usage; exit 0 ;;
		*) usage >&2; die 1 "unknown option $1" ;;
		esac
	done
	[ -n "$VERSION" ] || VERSION=$(env_get VERSION)
	[ -n "$VERSION" ] || VERSION=$TAG
	case $VERSION in v*) ;; *) VERSION="v$VERSION" ;; esac
	[ -n "$DIR" ] || DIR=$(env_get INSTALL_DIR)
	[ -n "$DIR" ] || DIR="$HOME/.local/bin"
	[ "$(env_get NO_HOOKS)" = 1 ] && NO_HOOKS=1
	if [ -z "$SELECTED" ]; then
		SELECTED=$PRODUCTS
	else
		# A product named twice is installed once.
		chosen=''
		for prod in $SELECTED; do
			in_list "$prod" "$PRODUCTS" || die 1 "$prod is not a product of this release ($PRODUCTS)"
			in_list "$prod" "$chosen" || chosen="$chosen $prod"
		done
		SELECTED=$chosen
	fi
	if [ "$(id -u)" = 0 ] && [ "$ALLOW_ROOT" != 1 ]; then
		die 1 "refusing to run as root; install into your own directory, or pass --allow-root"
	fi
	if [ "$UNINSTALL" = 1 ]; then
		uninstall
		return 0
	fi
	check_tag "$VERSION"
	set_base
	detect_platform
	for prod in $SELECTED; do
		[ -n "$(asset_for "$prod")" ] ||
			die 1 "$OS/$ARCH is not a platform of this release (it ships $(supported)); on Windows use install.ps1"
	done
	if [ "$VERIFY_ATTESTATION" = 1 ]; then
		command -v gh >/dev/null 2>&1 || die 1 "--verify-attestation needs gh"
		gh auth status >/dev/null 2>&1 || die 1 "--verify-attestation needs gh to be logged in (gh auth login)"
	fi
	if [ "$DRY_RUN" = 1 ]; then
		for prod in $SELECTED; do
			# shellcheck disable=SC2046 # asset_for prints two words.
			set -- $(asset_for "$prod")
			say "would download $BASE/$REPOSITORY/releases/download/$VERSION/$1 and install $DIR/$prod"
		done
		return 0
	fi

	mkdir -p "$DIR"
	# The PATH advice and every later path need DIR absolute.
	case $DIR in
	/*) ;;
	*) DIR=$(CDPATH='' cd -- "$DIR" && pwd) || die 1 "cannot resolve $DIR" ;;
	esac
	for prod in $SELECTED; do
		for f in "$DIR/$prod" "$DIR/$prod.prev"; do
			if [ -d "$f" ]; then
				die 1 "$f is a directory; nothing was changed"
			fi
		done
	done
	trap cleanup EXIT
	trap 'cleanup; exit 130' INT
	trap 'cleanup; exit 143' TERM
	WORK=$(mktemp -d "$DIR/.$INSTALLER_NAME-install.XXXXXX")
	fetch "$BASE/$REPOSITORY/releases/download/$VERSION/SHA256SUMS" "$WORK/SHA256SUMS" ||
		die 2 "download of SHA256SUMS for $VERSION failed"
	for prod in $SELECTED; do
		# shellcheck disable=SC2046 # asset_for prints two words.
		set -- $(asset_for "$prod")
		fetch_verified "$1" "$WORK/$1"
		extract "$prod" "$WORK/$1" "$2" "$WORK/$prod.new"
		chmod 0755 "$WORK/$prod.new"
	done

	run_hooks before_install "$DIR" || die 1 "a before_install hook failed; nothing was changed"
	for prod in $SELECTED; do
		if [ -e "$DIR/$prod" ]; then
			mv -f "$DIR/$prod" "$DIR/$prod.prev"
			PREVIOUS="$PREVIOUS $prod"
		fi
		mv -f "$WORK/$prod.new" "$DIR/$prod"
		SWAPPED="$SWAPPED $prod"
	done
	if ! check_identity "$DIR"; then
		restore "$DIR"
		die 2 "the new binaries do not report $VERSION; the previous ones were restored"
	fi
	for prod in $SELECTED; do
		say "installed $DIR/$prod ($VERSION)"
	done
	case ":$PATH:" in
	*":$DIR:"*) ;;
	*) say "add $DIR to your PATH, for example: export PATH=\"$DIR:\$PATH\"" ;;
	esac
	if ! run_hooks after_install "$DIR"; then
		err "installed, but an after_install hook failed"
		exit 3
	fi
	return 0
}

main "$@"
